import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import DesktopSidebar from "@/components/sidebar.component";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
     <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <DesktopSidebar />
        <main style={{ marginLeft: "260px", padding: "20px" }}>
          {children}
        </main>
      </body>
    </html>
  );
}
